### ISSUE TITLE
'rabbit_common' docset is missing

### ISSUE THREAD

**Issue by izimbra** [hexpm/hex_web#184]
http://hexdocs.pm/rabbit_common link is broken

**Comment by ericmj** [comment]
Have any docs been uploaded for that package? I can't seem to find any.

**Comment by ericmj** [comment]
Also, where did you find the link?

**Comment by izimbra** [comment]
I assumed - maybe incorrectly - that since the packages are on Hex, the docs are built automatically. 
The link comes from Dash (https://kapeli.com/dash) which tries to download docsets using the recipe from Hexdocs frontpage:
>To find documentation sets on Hexdocs, you can go to the following URLs:
> `http://hexdocs.pm/<package>/` - Latest documentation set for `package`

**Comment by ericmj** [comment]
Hex doesn't build docs automatically, package authors upload docs themselves by running `mix hex.docs` or something else for erlang packages.

**Comment by izimbra** [comment]
Building and publishing them automatically after package upload would be a nice feature.

**Comment by ericmj** [comment]
We are likely not going to add that because users can generate documentation however they want and I don't want to be running user code on the same server that handles packages. I created the documentation functionality because no service to host documentation existed at the time. Hex is package manager first and that's its main focus, it's not going to be a full featured documentation browser. If someone wants to build that service I would be very glad to integrate it with Hex and discontinue Hexdocs.

Also, building and publishing docs is literally one extra command `mix hex.docs` (or `rebar3 hex docs` for erlang packages) and we even remind you to do that.

**Comment by izimbra** [comment]
Thanks for the detailed explanation!
