### ISSUE TITLE
Problem with Sample Data

### ISSUE THREAD

**Issue by pragmaticivan** [hexpm/hex_web#192]
I'm having some trouble using sample data with Ecto:

<img width="953" alt="screen shot 2015-11-27 at 12 10 53 pm" src="https://cloud.githubusercontent.com/assets/301291/11447727/0e7e81de-9500-11e5-9d46-352272741ad0.png">

Looks like the validation system is not working very well.

**Comment by ericmj** [comment]
I think the validation is correct, I am just really bad at updating the sample data when I do incompatible changes because I use it infrequently myself. We should try to add the sample data to the tests.

**Comment by pragmaticivan** [comment]
I think it's an obstacle for new contributors. And Maybe is something that we should give more attention.  I'm new with Elixir and Ecto, I'm gonna try to fix that.

**Comment by pragmaticivan** [comment]
By the way, is there any parallel project for migrate this project to Phoenix?

**Comment by ericmj** [comment]
> I think it's an obstacle for new contributors. And Maybe is something that we should give more attention.

Definitely and if we make it a part of test suite this issue will not come up again.

> By the way, is there any parallel project for migrate this project to Phoenix?

We are going to convert to phoenix but first we need to change how we test the hex client. To test the client we make hex_web a dependency and test by calling it directly inside the same VM. Hex needs to support all elixir versions since 1.0.0 and phoenix doesn't support that, so first we need to move hex_web to an external process when testing. I am working on this but it's a big change so it will take some time.
