### ISSUE TITLE
metadata.config is not in sync with rebar.config

### ISSUE THREAD

**Issue by gleber** [hexpm/hex_web#208]
For example:
https://hex.pm/packages/jc

This page lists no deps, and it is reflected in it's metadata.config: http://ix.io/ntj
rebar.config looks like this: http://ix.io/ntk

What might have happened here? Does hex do metadata validation with the content of build configuration?

Triggering issue: https://github.com/erlang-nix/hex2nix/issues/4

**Comment by gleber** [comment]
@ericbmerritt FYI

**Comment by ericbmerritt** [comment]
This should probably be in hex rather than hex_web. I think hex_web really can't do validation considering it has no insight on the build system.

**Comment by tsloughter** [comment]
@gleber this can't be done by hex_web, it would restrict what tools are allowed to publish packages.

The issue here is the person publishing `jc` didn't have a `rebar.lock` so it didn't know it had deps to include in the package, and the user didn't check the output `rebar3_hex` gives where it lists what deps it discovered are to be included as being wrongly empty.

As a fix for this I've published a new version of `rebar3_hex` that makes publishing depend on the `lock` provider so that there is no way a user can ever publish a package without there being a `rebar.lock` generated first.

**Comment by gleber** [comment]
I see. Thanks for exaplanation. I do not yet know the architecture of ecosystem well enough. So it seems like we can close this issue.
