### ISSUE TITLE
Implement and document DMCA process

### ISSUE THREAD

**Issue by ericmj** [hexpm/hex_web#270]

**Comment by ericmj** [comment]
I'm guessing DMCA applies to hex.pm because it's hosted on Heroku and Amazon which are both US companies.

**Comment by ericmj** [comment]
Also add document on trademark disputes.

**Comment by jcspencer** [comment]
What do you think the process of DCMA takedowns and trademark dispute responses should look like?

**Comment by ericmj** [comment]
> What do you think the process of DCMA takedowns and trademark dispute responses should look like?

I don't know yet, that's why we have this issue :)

**Comment by paulcsmith** [comment]
Not sure if this helps, but bitlaw.com has a great writeup on trademark disputes: http://www.bitlaw.com/trademark/internet.html and specifically http://www.bitlaw.com/trademark/infringe.html

It looks like in the case of the Kik/npm ordeal it is very unlikely they actually would have had any legal grounds since. I'm quoting the parts that are most relevant

> To analyze whether a particular situation has developed the requisite "likelihood of confusion," courts have generally looked at the following eight factors:

> * the similarity in the overall impression created by the two marks (including the marks' look, phonetic similarities, and underlying meanings);
> * the similarities of the goods and services involved (including an examination of the marketing channels for the goods);
> * the strength of the plaintiff's mark;
> * any evidence of actual confusion by consumers;
> * the intent of the defendant in adopting its mark;
> * the physical proximity of the goods in the retail marketplace;
> * the degree of care likely to be exercised by the consumer; and
> * the likelihood of expansion of the product lines.

Only the top 5 would apply to this particular case, and IMO it would be pretty hard to prove that an npm package would cause confusion with a consumer chat app. 

My point in posting all this is not to debate whether the kik package was infringing, but to make sure packages aren't removed or renamed just because someone *claims* it infringes on a trademark. There must be real provable legal grounds for removal/rename. I hope this helps shape some of the policies for Hex in some way, and thanks Eric, for helping to make sure hex is robust and safe for it's users!

**Comment by ferd** [comment]
The problem with this is that if you do not take down the content, what is going to be the legal process if you decide to say no when someone sends you what looks like a bad trademark claim, but then decides to bring it to court anyway?

**Comment by paulcsmith** [comment]
I think if a court order looks legitimate then things should be taken down. In the case of Kik it was a threat with little/no legal backing. They did not sufficiently illustrate how it infringed. There is a definite gray area here, but if there is doubt, I think asking for legal proof before taking something down is not an unreasonable demand. If something is obviously an infringement maybe that is another story though?

**Comment by jcspencer** [comment]
There are some key things I would recommend implementing in this process:

- Provide a simple means of creating claims, as well as counter claims.
- *Fix Windows*: If the claim is due to a subset of files or code within the package, the user could be given a window of, for example, 24 hours to fix the issue. If the claim is in reference to the entire package, we would skip this step.
- *Repeated Infringement*: In appropriate circumstances, Hex could disable or terminate the accounts of users who may infringe upon the copyrights of others on **multiple** occasions.
- *Transparency*: The public should know what content is being removed from Hex and why. An informed public can notice and surface potential issues that would otherwise go unnoticed in an opaque system. We post redacted copies of any legal notices we receive.

**Comment by ericmj** [comment]
Closed in favour of #274.
