### ISSUE TITLE
Add latest_release field to `/api/packages`

### ISSUE THREAD

**Issue by enilsen16** [hexpm/hex_web#275]
When working with the api I am finding myself making multiple calls. One for a list of packages sorted by `updated_at` and another for a particular package's latest version.  

Two options that come to mind are adding a key for the latest version or batching API calls; for example, `https://hex.pm/api/packages/abnf,ecto` would return all information regarding both `abnf` and `ecto`.

**Comment by ferd** [comment]
behold as I create the `abnf,ecto` package and ruin your day

**Comment by ericmj** [comment]
We can include the list of published versions and their API links in the package index endpoint. Personally not a fan of the comma-separated list.

**Comment by enilsen16** [comment]
I implemented something similar -- https://github.com/enilsen16/hex_web/commit/6ee1b27b45651227c55d0fbd18db79ef87b101de

But I feel like this adds extra cruft. If I need all the versions of a given package, polling the api twice is fine. It's just in cases when you are looking for the latest version where I think this should be added to the index endpoint.

**Comment by ericmj** [comment]
The problem with the linked commit is the N+1 query, one query will be executed for every package in the result. It is possible to build a single query that fetches all releases for all packages.

The "latest version" means different things for different people. Is the latest published version, is it the version with the highest version numbers or is the highest version excluding pre-releases. That's why I think if we add this all releases of a package should be included so that clients can make this decision.
