### ISSUE TITLE
Implement per-package signing

### ISSUE THREAD

**Issue by jcspencer** [hexpm/hex_web#277]
After the recently infamous NPM fiasco, I believe it is essential that Hex provides users and developers with a means of personally signing and verifying the signatures of packages to ensure that packages have not been tampered with by a third party (thus removing the need to trust Hex, as well as the developer)

The easiest way to implement this functionality is probably to use porcelain or another abstraction to shell out to GPG, allowing the use of existing keystores, etc.

I'm unsure as to how users could provide GPG details of the developer they trust, but I assume it could be implemented in the mix file.

This is obviously not something that would be a default requirement, but having the functionality would allow a minority of users to feel safer pulling code from Hex.

**Comment by jcspencer** [comment]
Context: https://twitter.com/lhoguin/status/711248900749975553, http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm

**Comment by enilsen16** [comment]
@jcspencer I may be wrong but https://github.com/hexpm/hex/issues/216 might be what you are looking for.

**Comment by jcspencer** [comment]
Thanks for the reference, but this is not referring to a checksum of the file, as any party can create a checksum. A signature can only be created by a party with a certain key, which makes sure that a specific user created it. 

On 26 March 2016 10:26:53 PM AEDT, Erik Nilsen <notifications@github.com> wrote:
>@jcspencer I may be wrong but https://github.com/hexpm/hex/issues/216
>might be what you are looking for.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hexpm/hex_web/issues/277#issuecomment-201772433

-- 
James Spencer

**Comment by ericmj** [comment]
I would like to reiterate that the "NPM fiasco" is not possible on hex.pm. It's not possible for users to revert or re-publish packages and removed packages cannot be acquired by other users. There are also some recently opened issues that will strengthen the enforcement of this, we always appreciate any help we can get with issues.

I also want to say that getting package signing right is very difficult. If it was as easy as shelling out to GPG we would already have it in Hex :). A few requirements that we need to have for signing are:

1. No extra applications or dependencies to install (this is where GPG falls away unfortunately)
2. Easy to sign a package you publish
3. Easy and quick to verify a package and verify that the owner is who he says he is - even when working with many (30+) packages
4. No dependency on hex.pm as central authority

The important thing with package signing is adoption. If a single one of your dependencies isn't signed and verified it doesn't matter that the rest of your dependencies are signed. So it needs to be so quick and painless that everyone will do it or that we can just enforce it on all package owners.

We have discussed package signing many times before and have put it on hold because no proposal has been put forth that satisfies the above requirements. I don't think it's productive to start this discussion again until we have a concrete proposal or at least an idea for an approach that can satisfy our requirements.

I also believe that we shouldn't leave issues open that aren't directly actionable [1] and I will therefor close this issue. I also want to make it perfectly clear that I am not dismissing the idea of user-signed packages, it's a hard problem and one that I think about constantly, I would be very happy if we had a proposal or idea from which we can start working on.

If you want to start a general discussion about this problem I suggest the Elixir or Erlang mailing lists as appropriate forums and I would be glad to take part of the discussion there.

[1] http://blog.plataformatec.com.br/2014/05/tips-for-keeping-your-open-source-software-issues-tracker-tidy

**Comment by jcspencer** [comment]
Thanks for the swift, lengthy reply!

In regards to the NPM issue, I don't believe the issue lies with other users being able to republish packages in place of existing revisions, but rather that NPM itself was able to do so. This could obviously avoided by making the registry completely immutable, but a signature proves that nobody other than the developer touched it.

In regards to the rest of your response, I agree completely. "Shelling out to gpg" is very much a band-aid solution to a problem that could be solved in a much better way, I will open an issue on the elixir mailing list.
