### ISSUE TITLE
Redirect hexdocs.pm/package

### ISSUE THREAD

**Issue by josevalim** [hexpm/hex_web#87]
Today, it seems we are serving packages from hexdocs.pm/package but we should rather redirect otherwise we can have caching issues. There is an html-refresh meta tag thing we can (ab)use. For example, some people are experiencing caching issues with [Phoenix](http://hexdocs.pm/phoenix/0.8.0/)

**Comment by ericmj** [comment]
We changed to serve the latest docs from hexdocs.pm/package instead of redirecting to the latest version because people complained that they couldn't create links to the latest docs. The HTTP cache headers are set to 1 hour, so it shouldn't be too big of an issue. Setting the cache time lower will update the page faster but will also likely result in a slower website.

**Comment by ericmj** [comment]
I have decided to keep the current behaviour but lower the cached headers to 15min. Waiting 15mins for docs to update should be fine.

**Comment by ericmj** [comment]
With the free option on cloudflare we can only set the browser expire TTL to 30 min and the edge cache TTL to 2 hours.
